name: salo
description: "Seja o seu próprio boss."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #firebase_core: ^2.24.2
  #firebase_auth: ^4.16.0
  #firebase_messaging: ^14.9.4
  cupertino_icons: ^1.0.6
  auto_route: ^9.2.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  auto_route_generator: ^9.0.0
  flutter_gen_runner: ^5.2.0
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# Assets generator
flutter_gen:
  output: lib/shared/gen/ # Optional (default: lib/gen/)
  integrations:
    flutter_svg: true
  assets:
    outputs:
      class_name: Assets # Optional (default: Assets)

flutter:
  uses-material-design: true
  assets:
     - assets/
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700